# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'LocationTracking' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Firebase/AdMob'
	pod 'GoogleMaps'
	pod 'GooglePlaces'
  	pod 'RappleProgressHUD'
	pod 'Firebase', '>= 2.5.0'
	pod 'FirebaseCore’
	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
	pod 'Firebase/Crash'
	pod 'Firebase/Database'
	pod 'Alamofire'
	pod 'SwiftyJSON'
end
